### ISSUE TITLE
New Rule: Prevent usage of `<button>` with Next.js `Link` component

### ISSUE THREAD

**Issue by karlhorky** [upleveled/eslint-plugin-upleveled#19]
The following should be errors / warnings:

```jsx
<button>
  <Link href="/checkout">
    <a>Buy now</a>
  </Link>
</button>
```

```jsx
<Link href="/checkout" passHref>
  <button>Buy now</button>
</Link>
```

**Comment by Josehower** [comment]
Related to #20 #21 #140

**Comment by Josehower** [comment]
Related to [#20](https://github.com/upleveled/eslint-plugin-upleveled/issues/20) [#21](https://github.com/upleveled/eslint-plugin-upleveled/issues/21)  [140](https://github.com/upleveled/preflight/issues/140)
