### ISSUE TITLE
New Rule: Form without `event.preventDefault` in `onSubmit`

### ISSUE THREAD

**Issue by karlhorky** [upleveled/eslint-plugin-upleveled#21]
Many students run into the issue of forgetting to use `event.preventDefault` in their onSubmit, leading to longer debugging sessions

Since we teach to always prevent the default and manually handle the form submission using `fetch`, we can warn on this

**Comment by Josehower** [comment]
Related to [#20](https://github.com/upleveled/eslint-plugin-upleveled/issues/20) [#19](https://github.com/upleveled/eslint-plugin-upleveled/issues/19) [140](https://github.com/upleveled/preflight/issues/140)

**Comment by karlhorky** [comment]
Done in https://github.com/upleveled/eslint-plugin-upleveled/releases/tag/v2.1.0 and https://github.com/upleveled/eslint-config-upleveled/releases/tag/v2.3.0
